/*
 * types.h
 *
 *  Created on: Nov 18, 2012
 *      Author: pag
 */

#ifndef GR_KERNEL_TYPES_H_
#define GR_KERNEL_TYPES_H_

#ifdef LINUX
#   include <linux/version.h>
#   define LINUX_MAJOR_VERSION ((LINUX_VERSION_CODE >> 16) & 0xFF)
#   define LINUX_MINOR_VERSION ((LINUX_VERSION_CODE >> 8)  & 0xFF)
#   define LINUX_PATCH_VERSION ((LINUX_VERSION_CODE >> 0)  & 0xFF)
#endif

#ifdef __cplusplus
namespace kernel {
extern "C" {
#endif

#include <linux/acct.h>
#include <linux/coda.h>
#include <linux/hdlc.h>
#include <linux/ipmi_msgdefs.h>
#include <linux/ncp_mount.h>
#include <linux/ppp_defs.h>
#include <linux/sysinfo.h>
#include <linux/adb.h>
#include <linux/coda_psdev.h>
#include <linux/hdreg.h>
#include <linux/ipsec.h>
#include <linux/ncp_no.h>
#include <linux/ppp-ioctl.h>
#include <linux/taskstats.h>
#include <linux/adfs_fs.h>
#include <linux/coff.h>
#include <linux/hiddev.h>
#include <linux/ipv6.h>
#include <linux/neighbour.h>
#include <linux/pps.h>
//#include <linux/tc_act>
#include <linux/affs_hardblocks.h>
#include <linux/comstats.h>
#include <linux/hid.h>
#include <linux/ipv6_route.h>
#include <linux/netdevice.h>
#include <linux/prctl.h>
//#include <linux/tc_ematch>
#include <linux/agpgart.h>
#include <linux/connector.h>
#include <linux/hidraw.h>
#include <linux/ip_vs.h>
#include <linux/net_dropmon.h>
#include <linux/ptp_clock.h>
#include <linux/tcp.h>
#include <linux/aio_abi.h>
#include <linux/const.h>
#include <linux/hpet.h>
#include <linux/ipx.h>
//#include <linux/netfilter>
#include <linux/ptrace.h>
#include <linux/telephony.h>
#include <linux/a.out.h>
#include <linux/cramfs_fs.h>
//#include <linux/hsi>
#include <linux/irda.h>
//#include <linux/netfilter_arp>
#include <linux/qnx4_fs.h>
#include <linux/termios.h>
#include <linux/apm_bios.h>
#include <linux/cuda.h>
#include <linux/hysdn_if.h>
#include <linux/irqnr.h>
#include <linux/netfilter_arp.h>
#include <linux/qnxtypes.h>
#include <linux/time.h>
#include <linux/arcfb.h>
#include <linux/cyclades.h>
#include <linux/i2c-dev.h>
//#include <linux/isdn>
//#include <linux/netfilter_bridge>
#include <linux/quota.h>
#include <linux/times.h>
#include <linux/atalk.h>
#include <linux/cycx_cfm.h>
#include <linux/i2c.h>
#include <linux/isdn_divertif.h>
#include <linux/netfilter_bridge.h>
#include <linux/radeonfb.h>
#include <linux/timex.h>
#include <linux/atmapi.h>
#include <linux/dcbnl.h>
#include <linux/i2o-dev.h>
#include <linux/isdn.h>
#include <linux/netfilter_decnet.h>
//#include <linux/raid>
#include <linux/tiocl.h>
#include <linux/atmarp.h>
#include <linux/dccp.h>
#include <linux/i8k.h>
#include <linux/isdnif.h>
#include <linux/netfilter.h>
#include <linux/random.h>
#include <linux/tipc_config.h>
#include <linux/atmbr2684.h>
#include <linux/dlmconstants.h>
#include <linux/icmp.h>
#include <linux/isdn_ppp.h>
//#include <linux/netfilter_ipv4>
#include <linux/raw.h>
#include <linux/tipc.h>
#include <linux/atmclip.h>
#include <linux/dlm_device.h>
#include <linux/icmpv6.h>
#include <linux/iso_fs.h>
#include <linux/netfilter_ipv4.h>
#include <linux/rds.h>
#include <linux/toshiba.h>
#include <linux/atmdev.h>
#include <linux/dlm.h>
#include <linux/if_addr.h>
#include <linux/ivtvfb.h>
//#include <linux/netfilter_ipv6>
#include <linux/reboot.h>
#include <linux/tty.h>
#include <linux/atm_eni.h>
#include <linux/dlm_netlink.h>
#include <linux/if_addrlabel.h>
#include <linux/ivtv.h>
#include <linux/netfilter_ipv6.h>
#include <linux/reiserfs_fs.h>
#include <linux/types.h>
#include <linux/atm.h>
#include <linux/dlm_plock.h>
#include <linux/if_alg.h>
#include <linux/ixjuser.h>
#include <linux/net.h>
#include <linux/reiserfs_xattr.h>
#include <linux/udf_fs_i.h>
#include <linux/atm_he.h>
#include <linux/dm-ioctl.h>
#include <linux/if_arcnet.h>
#include <linux/jffs2.h>
#include <linux/netlink.h>
#include <linux/resource.h>
#include <linux/udp.h>
#include <linux/atm_idt77105.h>
#include <linux/dm-log-userspace.h>
#include <linux/if_arp.h>
#include <linux/joystick.h>
#include <linux/netrom.h>
#include <linux/rfkill.h>
#include <linux/uinput.h>
#include <linux/atmioc.h>
#include <linux/dn.h>
#include <linux/if_bonding.h>
#include <linux/kdev_t.h>
#include <linux/net_tstamp.h>
#include <linux/romfs_fs.h>
#include <linux/uio.h>
#include <linux/atmlec.h>
#include <linux/dqblk_xfs.h>
#include <linux/if_bridge.h>
#include <linux/kd.h>
#include <linux/nfc.h>
#include <linux/rose.h>
#include <linux/ultrasound.h>
#include <linux/atmmpc.h>
//#include <linux/dvb>
#include <linux/if_cablemodem.h>
#include <linux/kernelcapi.h>
#include <linux/nfs2.h>
#include <linux/route.h>
#include <linux/un.h>
#include <linux/atm_nicstar.h>
#include <linux/edd.h>
#include <linux/if_eql.h>
#include <linux/kernel.h>
#include <linux/nfs3.h>
#include <linux/rtc.h>
#include <linux/unistd.h>
#include <linux/atmppp.h>
#include <linux/efs_fs_sb.h>
#include <linux/if_ether.h>
#include <linux/kernel-page-flags.h>
#include <linux/nfs4.h>
#include <linux/rtnetlink.h>
#include <linux/unix_diag.h>
#include <linux/atmsap.h>
#include <linux/elfcore.h>
#include <linux/if_fc.h>
#include <linux/kexec.h>
#include <linux/nfs4_mount.h>
#include <linux/scc.h>
//#include <linux/usb>
#include <linux/atmsvc.h>
#include <linux/elf-em.h>
#include <linux/if_fddi.h>
#include <linux/keyboard.h>
#include <linux/nfsacl.h>
#include <linux/sched.h>
#include <linux/usbdevice_fs.h>
#include <linux/atm_tcp.h>
#include <linux/elf-fdpic.h>
#include <linux/if_frad.h>
#include <linux/keyctl.h>
//#include <linux/nfsd>
#include <linux/screen_info.h>
#include <linux/utime.h>
#include <linux/atm_zatm.h>
#include <linux/elf.h>
#include <linux/if.h>
#include <linux/kvm.h>
#include <linux/nfs_fs.h>
#include <linux/sdla.h>
#include <linux/utsname.h>
#include <linux/audit.h>
#include <linux/errno.h>
#include <linux/if_hippi.h>
#include <linux/kvm_para.h>
#include <linux/nfs.h>
#include <linux/seccomp.h>
#include <linux/uuid.h>
#include <linux/aufs_type.h>
#include <linux/errqueue.h>
#include <linux/if_infiniband.h>
#include <linux/l2tp.h>
#include <linux/nfs_idmap.h>
#include <linux/securebits.h>
#include <linux/uvcvideo.h>
#include <linux/auto_fs4.h>
#include <linux/ethtool.h>
#include <linux/if_link.h>
#include <linux/limits.h>
#include <linux/nfs_mount.h>
#include <linux/selinux_netlink.h>
#include <linux/v4l2-dv-timings.h>
#include <linux/auto_fs.h>
#include <linux/eventpoll.h>
#include <linux/if_ltalk.h>
#include <linux/llc.h>
#include <linux/nl80211.h>
#include <linux/sem.h>
#include <linux/v4l2-mediabus.h>
#include <linux/auxvec.h>
#include <linux/fadvise.h>
#include <linux/if_packet.h>
#include <linux/loop.h>
#include <linux/n_r3964.h>
#include <linux/serial_core.h>
#include <linux/v4l2-subdev.h>
#include <linux/ax25.h>
#include <linux/falloc.h>
#include <linux/if_phonet.h>
#include <linux/lp.h>
#include <linux/nubus.h>
#include <linux/serial.h>
#include <linux/version.h>
#include <linux/b1lli.h>
#include <linux/fanotify.h>
#include <linux/if_plip.h>
#include <linux/magic.h>
#include <linux/nvram.h>
#include <linux/serial_reg.h>
#include <linux/veth.h>
#include <linux/baycom.h>
#include <linux/fb.h>
#include <linux/if_ppp.h>
#include <linux/major.h>
#include <linux/omap3isp.h>
#include <linux/serio.h>
#include <linux/vhost.h>
#include <linux/bfs_fs.h>
#include <linux/fcntl.h>
#include <linux/if_pppol2tp.h>
#include <linux/map_to_7segment.h>
#include <linux/omapfb.h>
#include <linux/shm.h>
#include <linux/videodev2.h>
#include <linux/binfmts.h>
#include <linux/fd.h>
#include <linux/if_pppox.h>
#include <linux/matroxfb.h>
#include <linux/oom.h>
#include <linux/signalfd.h>
#include <linux/virtio_9p.h>
#include <linux/blkpg.h>
#include <linux/fdreg.h>
#include <linux/if_slip.h>
#include <linux/mdio.h>
#include <linux/param.h>
#include <linux/signal.h>
#include <linux/virtio_balloon.h>
#include <linux/blktrace_api.h>
#include <linux/fib_rules.h>
#include <linux/if_strip.h>
#include <linux/media.h>
#include <linux/parport.h>
#include <linux/snmp.h>
#include <linux/virtio_blk.h>
#include <linux/blk_types.h>
#include <linux/fiemap.h>
#include <linux/if_team.h>
#include <linux/mei.h>
//#include <linux/patchkey.h>
#include <linux/sock_diag.h>
#include <linux/virtio_config.h>
#include <linux/bpqether.h>
#include <linux/filter.h>
#include <linux/if_tun.h>
#include <linux/mempolicy.h>
#include <linux/pci.h>
#include <linux/socket.h>
#include <linux/virtio_console.h>
#include <linux/bsg.h>
#include <linux/firewire-cdev.h>
#include <linux/if_tunnel.h>
#include <linux/meye.h>
#include <linux/pci_regs.h>
#include <linux/sockios.h>
#include <linux/virtio_ids.h>
//#include <linux/byteorder>
#include <linux/firewire-constants.h>
#include <linux/if_vlan.h>
#include <linux/mii.h>
#include <linux/perf_event.h>
#include <linux/som.h>
#include <linux/virtio_net.h>
//#include <linux/caif>
#include <linux/flat.h>
#include <linux/if_x25.h>
#include <linux/minix_fs.h>
#include <linux/personality.h>
#include <linux/sonet.h>
#include <linux/virtio_pci.h>
//#include <linux/can>
#include <linux/fs.h>
#include <linux/igmp.h>
#include <linux/mman.h>
#include <linux/pfkeyv2.h>
#include <linux/sonypi.h>
#include <linux/virtio_ring.h>
#include <linux/can.h>
#include <linux/fsl_hypervisor.h>
#include <linux/in6.h>
//#include <linux/mmc>
#include <linux/pg.h>
#include <linux/soundcard.h>
#include <linux/virtio_rng.h>
#include <linux/capability.h>
#include <linux/fuse.h>
#include <linux/inet_diag.h>
#include <linux/mmtimer.h>
#include <linux/phantom.h>
#include <linux/sound.h>
#include <linux/vt.h>
#include <linux/capi.h>
#include <linux/futex.h>
#include <linux/in.h>
#include <linux/mqueue.h>
#include <linux/phonet.h>
//#include <linux/spi>
#include <linux/wait.h>
#include <linux/cciss_defs.h>
#include <linux/gameport.h>
#include <linux/inotify.h>
#include <linux/mroute6.h>
#include <linux/pktcdvd.h>
#include <linux/stat.h>
#include <linux/wanrouter.h>
#include <linux/cciss_ioctl.h>
//#include <linux/generic_serial.h>
#include <linux/input.h>
#include <linux/mroute.h>
#include <linux/pkt_cls.h>
#include <linux/stddef.h>
#include <linux/watchdog.h>
#include <linux/cdk.h>
#include <linux/genetlink.h>
#include <linux/in_route.h>
#include <linux/msdos_fs.h>
#include <linux/pkt_sched.h>
#include <linux/string.h>
//#include <linux/wimax>
#include <linux/cdrom.h>
#include <linux/gen_stats.h>
#include <linux/ioctl.h>
#include <linux/msg.h>
#include <linux/pmu.h>
//#include <linux/sunrpc>
#include <linux/wimax.h>
#include <linux/cgroupstats.h>
#include <linux/gfs2_ondisk.h>
#include <linux/ip6_tunnel.h>
#include <linux/mtio.h>
#include <linux/poll.h>
#include <linux/suspend_ioctls.h>
#include <linux/wireless.h>
#include <linux/chio.h>
#include <linux/gigaset_dev.h>
#include <linux/ipc.h>
#include <linux/nbd.h>
#include <linux/posix_types.h>
#include <linux/swab.h>
#include <linux/x25.h>
#include <linux/cm4000_cs.h>
//#include <linux/hdlc>
#include <linux/ip.h>
#include <linux/ncp_fs.h>
#include <linux/ppdev.h>
#include <linux/synclink.h>
#include <linux/xattr.h>
#include <linux/cn_proc.h>
#include <linux/hdlcdrv.h>
#include <linux/ipmi.h>
#include <linux/ncp.h>
#include <linux/ppp-comp.h>
#include <linux/sysctl.h>
#include <linux/xfrm.h>


#if 0
#if LINUX_MAJOR_VERSION == 3 && LINUX_MINOR_VERSION == 5
#	  include "granary/kernel/linux/3.5.0/kernel.h"
#elif LINUX_MAJOR_VERSION == 2 && LINUX_MINOR_VERSION == 6 && LINUX_PATCH_VERSION == 33
#   include "granary/kernel/linux/2.6.33/kernel.h"
#else
#   warning "Defaulting to Linux 2.6.33 kernel types."
#	  include "granary/kernel/linux/2.6.33/kernel.h"
#endif
#endif

#ifdef __cplusplus
} /* extern */
} /* kernel namespace */
#endif

#endif /* GR_KERNEL_TYPES_H_ */
