/* Copyright 2012-2013 Peter Goodman, all rights reserved. */
/*
 * posix.h
 *
 *      Author: Peter Goodman
 */

#ifndef granary_POSIX_TYPES_H_
#define granary_POSIX_TYPES_H_

#ifndef _GNU_SOURCE
#   define _GNU_SOURCE
#endif


#define GR_USING_GLIBC \
    (defined(__GLIBC__) || defined(__GNU_LIBRARY__) || defined(__GLIBC_MINOR__))

#ifndef _XOPEN_SOURCE
#   define _XOPEN_SOURCE
#endif


#if GR_USING_GLIBC || defined(__linux)
extern void *__libc_malloc(uint64_t);
extern void *__libc_calloc(uint64_t, uint64_t);
extern void *__libc_realloc(void *, uint64_t);
extern void __libc_free(void *);
#endif

// Some standard libraries use C99 specifier within array decl, e.g. `... [ __restrict ]`.
#define __restrict

#include </usr/include/aalib.h>
#include </usr/include/execinfo.h>
#include </usr/include/ldap.h>
#include </usr/include/OMX_Index.h>
#include </usr/include/syscall.h>
#include </usr/include/aio.h>
#include </usr/include/expat_external.h>
#include </usr/include/ldap_schema.h>
#include </usr/include/OMX_IVCommon.h>
#include </usr/include/sysexits.h>
#include </usr/include/aliases.h>
#include </usr/include/expat.h>
#include </usr/include/ldap_utf8.h>
#include </usr/include/OMX_Other.h>
#include </usr/include/syslog.h>
#include </usr/include/alloca.h>
#include </usr/include/faad.h>
#include </usr/include/ldif.h>
#include </usr/include/OMX_Types.h>
#include </usr/include/tar.h>
#include </usr/include/ansidecl.h>
#include </usr/include/fam.h>
#include </usr/include/libelf.h>
#include </usr/include/OMX_Video.h>
#include </usr/include/termcap.h>
#include </usr/include/argp.h>
#include </usr/include/fcntl.h>
#include </usr/include/libgen.h>
#include </usr/include/panel.h>
#include </usr/include/term_entry.h>
#include </usr/include/argz.h>
#include </usr/include/fdd.h>
#include </usr/include/libintl.h>
#include </usr/include/paths.h>
#include </usr/include/term.h>
#include </usr/include/ar.h>
#include </usr/include/features.h>
#include </usr/include/libio.h>
#include </usr/include/pcrecpparg.h>
#include </usr/include/termio.h>
#include </usr/include/assert.h>
#include </usr/include/fenv.h>
#include </usr/include/libmtp.h>
#include </usr/include/pcrecpp.h>
#include </usr/include/termios.h>
#include </usr/include/autosprintf.h>
#include </usr/include/FlexLexer.h>
#include </usr/include/libspeechd.h>
#include </usr/include/pcre.h>
#include </usr/include/tgmath.h>
#include </usr/include/bdd.h>
#include </usr/include/fluidsynth.h>
#include </usr/include/libssh2.h>
#include </usr/include/pcreposix.h>
#include </usr/include/thread_db.h>
#include </usr/include/bfd.h>
#include </usr/include/fmtmsg.h>
#include </usr/include/libssh2_publickey.h>
#include </usr/include/pcre_scanner.h>
#include </usr/include/tic.h>
#include </usr/include/bfdlink.h>
#include </usr/include/fnmatch.h>
#include </usr/include/libssh2_sftp.h>
#include </usr/include/pcre_stringpiece.h>
#include </usr/include/time.h>
#include </usr/include/brlapi_constants.h>
#include </usr/include/form.h>
#include </usr/include/libtar.h>
#include </usr/include/plugin-api.h>
#include </usr/include/tld.h>
#include </usr/include/brlapi.h>
#include </usr/include/fpu_control.h>
#include </usr/include/libtar_listhash.h>
#include </usr/include/pngconf.h>
#include </usr/include/ttyent.h>
#include </usr/include/brlapi_keycodes.h>
#include </usr/include/fstab.h>
#include </usr/include/libtasn1.h>
#include </usr/include/png.h>
#include </usr/include/turbojpeg.h>
#include </usr/include/brlapi_protocol.h>
#include </usr/include/fts.h>
#include </usr/include/libudev.h>
#include </usr/include/poll.h>
#include </usr/include/twolame.h>
#include </usr/include/bvec.h>
#include </usr/include/ftw.h>
#include </usr/include/libv4l1.h>
#include </usr/include/pr29.h>
#include </usr/include/uchar.h>
#include </usr/include/byteswap.h>
#include </usr/include/gbm.h>
#include </usr/include/libv4l1-videodev.h>
#include </usr/include/printf.h>
#include </usr/include/ucontext.h>
#include </usr/include/bzlib.h>
#include </usr/include/_G_config.h>
#include </usr/include/libv4l2.h>
#include </usr/include/profile.h>
#include </usr/include/ulimit.h>
#include </usr/include/caca0.h>
#include </usr/include/gconv.h>
#include </usr/include/libv4l2rds.h>
#include </usr/include/pthread.h>
#include </usr/include/unctrl.h>
#include </usr/include/caca_conio.h>
#include </usr/include/gcrypt.h>
#include </usr/include/libv4lconvert.h>
#include </usr/include/pty.h>
#include </usr/include/unistd.h>
#include </usr/include/caca.h>
#include </usr/include/gcrypt-module.h>
#include </usr/include/libv4l-plugin.h>
#include </usr/include/punycode.h>
#include </usr/include/ustat.h>
#include </usr/include/caca++.h>
#include </usr/include/gelf.h>
#include </usr/include/libyasm.h>
#include </usr/include/pwd.h>
#include </usr/include/utime.h>
#include </usr/include/caca_types.h>
#include </usr/include/getopt.h>
#include </usr/include/libyasm-stdint.h>
#include </usr/include/re_comp.h>
#include </usr/include/utmp.h>
#include </usr/include/chromaprint.h>
#include </usr/include/gettext-po.h>
#include </usr/include/libzvbi.h>
#include </usr/include/regex.h>
#include </usr/include/utmpx.h>
#include </usr/include/com_err.h>
#include </usr/include/glob.h>
#include </usr/include/limits.h>
#include </usr/include/regexp.h>
#include </usr/include/values.h>
#include </usr/include/complex.h>
//#include </usr/include/gmpxx.h>
#include </usr/include/link.h>
#include </usr/include/resolv.h>
#include </usr/include/wait.h>
#include </usr/include/cpio.h>
#include </usr/include/gnu-versions.h>
#include </usr/include/locale.h>
#include </usr/include/samplerate.h>
#include </usr/include/wayland-client.h>
#include </usr/include/crypt.h>
#include </usr/include/gpg-error.h>
#include </usr/include/ltdl.h>
#include </usr/include/sched.h>
#include </usr/include/wayland-client-protocol.h>
#include </usr/include/ctype.h>
#include </usr/include/grp.h>
#include </usr/include/lzma.h>
#include </usr/include/search.h>
#include </usr/include/wayland-cursor.h>
#include </usr/include/cucul.h>
#include </usr/include/gshadow.h>
#include </usr/include/mad.h>
#include </usr/include/semaphore.h>
#include </usr/include/wayland-egl.h>
#include </usr/include/cursesapp.h>
#include </usr/include/gssapi.h>
#include </usr/include/malloc.h>
#include </usr/include/setjmp.h>
#include </usr/include/wayland-server.h>
#include </usr/include/cursesf.h>
#include </usr/include/iconv.h>
#include </usr/include/math.h>
#include </usr/include/sgtty.h>
#include </usr/include/wayland-server-protocol.h>
#include </usr/include/curses.h>
#include </usr/include/idna.h>
#include </usr/include/mcheck.h>
#include </usr/include/shadow.h>
#include </usr/include/wayland-util.h>
#include </usr/include/cursesm.h>
#include </usr/include/idn-free.h>
#include </usr/include/memory.h>
#include </usr/include/signal.h>
#include </usr/include/wayland-version.h>
#include </usr/include/cursesp.h>
#include </usr/include/idn-int.h>
#include </usr/include/menu.h>
#include </usr/include/slang.h>
#include </usr/include/wchar.h>
#include </usr/include/cursesw.h>
#include </usr/include/ifaddrs.h>
#include </usr/include/mntent.h>
#include </usr/include/slcurses.h>
#include </usr/include/wctype.h>
#include </usr/include/cursslk.h>
#include </usr/include/inttypes.h>
#include </usr/include/monetary.h>
#include </usr/include/sndfile.h>
#include </usr/include/wordexp.h>
#include </usr/include/dca.h>
#include </usr/include/iomp.h>
#include </usr/include/mqueue.h>
#include </usr/include/spawn.h>
#include </usr/include/x264_config.h>
#include </usr/include/dialog.h>
#include </usr/include/iomp_lib.h>
#include </usr/include/nc_tparm.h>
#include </usr/include/spd_audio_plugin.h>
#include </usr/include/x264.h>
#include </usr/include/dirent.h>
#include </usr/include/jbig85.h>
#include </usr/include/ncurses_dll.h>
#include </usr/include/speechd_types.h>
//#include </usr/include/xf86drm.h>
#include </usr/include/dis-asm.h>
#include </usr/include/jbig_ar.h>
#include </usr/include/ncurses.h>
#include </usr/include/sqlite3ext.h>
//#include </usr/include/xf86drmMode.h>
#include </usr/include/dlfcn.h>
#include </usr/include/jbig.h>
#include </usr/include/neaacdec.h>
#include </usr/include/sqlite3.h>
#include </usr/include/xlocale.h>
#include </usr/include/dlg_colors.h>
#include </usr/include/jerror.h>
#include </usr/include/netdb.h>
#include </usr/include/stab.h>
#include </usr/include/z3_algebraic.h>
#include </usr/include/dlg_config.h>
#include </usr/include/jmorecfg.h>
#include </usr/include/nlist.h>
#include </usr/include/stdc-predef.h>
#include </usr/include/z3_api.h>
#include </usr/include/dlg_keys.h>
#include </usr/include/jpegint.h>
#include </usr/include/nl_types.h>
#include </usr/include/stdint.h>
#include </usr/include/z3_fpa.h>
#include </usr/include/elf.h>
#include </usr/include/jpeglib.h>
#include </usr/include/nss.h>
#include </usr/include/stdio_ext.h>
#include </usr/include/z3.h>
#include </usr/include/enca.h>
#include </usr/include/kdb.h>
#include </usr/include/obstack.h>
#include </usr/include/stdio.h>
#include </usr/include/z3++.h>
#include </usr/include/endian.h>
#include </usr/include/krb5.h>
#include </usr/include/omp.h>
#include </usr/include/stdlib.h>
#include </usr/include/z3_interp.h>
#include </usr/include/envz.h>
#include </usr/include/langinfo.h>
#include </usr/include/omp_lib.h>
#include </usr/include/string.h>
#include </usr/include/z3_macros.h>
#include </usr/include/err.h>
#include </usr/include/lastlog.h>
#include </usr/include/OMX_Audio.h>
#include </usr/include/stringprep.h>
#include </usr/include/z3_polynomial.h>
#include </usr/include/errno.h>
#include </usr/include/lber.h>
#include </usr/include/OMX_Component.h>
#include </usr/include/strings.h>
#include </usr/include/z3_rcf.h>
#include </usr/include/error.h>
#include </usr/include/lber_types.h>
#include </usr/include/OMX_ContentPipe.h>
#include </usr/include/stropts.h>
#include </usr/include/z3_v1.h>
#include </usr/include/eti.h>
#include </usr/include/ldap_cdefs.h>
#include </usr/include/OMX_Core.h>
#include </usr/include/sudo_plugin.h>
#include </usr/include/zlib.h>
#include </usr/include/etip.h>
#include </usr/include/ldap_features.h>
#include </usr/include/OMX_Image.h>
#include </usr/include/symcat.h>

#include </usr/include/sys/acct.h>
#include </usr/include/sys/fsuid.h>
#include </usr/include/sys/pci.h>
#include </usr/include/sys/sem.h>
#include </usr/include/sys/sysinfo.h>
#include </usr/include/sys/un.h>
#include </usr/include/sys/asoundlib.h>
#include </usr/include/sys/gmon.h>
#include </usr/include/sys/perm.h>
#include </usr/include/sys/sendfile.h>
#include </usr/include/sys/syslog.h>
#include </usr/include/sys/unistd.h>
#include </usr/include/sys/auxv.h>
#include </usr/include/sys/gmon_out.h>
#include </usr/include/sys/personality.h>
#include </usr/include/sys/shm.h>
#include </usr/include/sys/sysmacros.h>
#include </usr/include/sys/user.h>
#include </usr/include/sys/bitypes.h>
#include </usr/include/sys/inotify.h>
#include </usr/include/sys/poll.h>
#include </usr/include/sys/signalfd.h>
#include </usr/include/sys/termios.h>
#include </usr/include/sys/ustat.h>
#include </usr/include/sys/capability.h>
#include </usr/include/sys/ioctl.h>
#include </usr/include/sys/prctl.h>
#include </usr/include/sys/signal.h>
#include </usr/include/sys/timeb.h>
#include </usr/include/sys/utsname.h>
#include </usr/include/sys/cdefs.h>
#include </usr/include/sys/io.h>
#include </usr/include/sys/procfs.h>
#include </usr/include/sys/socket.h>
#include </usr/include/sys/time.h>
#include </usr/include/sys/vfs.h>
#include </usr/include/sys/debugreg.h>
#include </usr/include/sys/ipc.h>
#include </usr/include/sys/profil.h>
#include </usr/include/sys/socketvar.h>
#include </usr/include/sys/timerfd.h>
#include </usr/include/sys/vlimit.h>
#include </usr/include/sys/dir.h>
#include </usr/include/sys/kdaemon.h>
#include </usr/include/sys/ptrace.h>
#include </usr/include/sys/soundcard.h>
#include </usr/include/sys/times.h>
//#include </usr/include/sys/vm86.h>
//#include </usr/include/sys/elf.h>
#include </usr/include/sys/kd.h>
#include </usr/include/sys/queue.h>
#include </usr/include/sys/statfs.h>
#include </usr/include/sys/timex.h>
#include </usr/include/sys/vt.h>
#include </usr/include/sys/epoll.h>
#include </usr/include/sys/klog.h>
#include </usr/include/sys/quota.h>
#include </usr/include/sys/stat.h>
#include </usr/include/sys/ttychars.h>
#include </usr/include/sys/vtimes.h>
#include </usr/include/sys/errno.h>
#include </usr/include/sys/mman.h>
#include </usr/include/sys/raw.h>
#include </usr/include/sys/statvfs.h>
#include </usr/include/sys/ttydefaults.h>
#include </usr/include/sys/wait.h>
#include </usr/include/sys/eventfd.h>
#include </usr/include/sys/mount.h>
#include </usr/include/sys/reboot.h>
#include </usr/include/sys/stropts.h>
#include </usr/include/sys/types.h>
#include </usr/include/sys/xattr.h>
#include </usr/include/sys/fanotify.h>
#include </usr/include/sys/msg.h>
#include </usr/include/sys/reg.h>
#include </usr/include/sys/swap.h>
#include </usr/include/sys/ucontext.h>
#include </usr/include/sys/fcntl.h>
#include </usr/include/sys/mtio.h>
#include </usr/include/sys/resource.h>
#include </usr/include/sys/syscall.h>
#include </usr/include/sys/uio.h>
#include </usr/include/sys/file.h>
#include </usr/include/sys/param.h>
#include </usr/include/sys/select.h>
#include </usr/include/sys/sysctl.h>
#include </usr/include/sys/ultrasound.h>
#ifdef __GR_HAS_CPP
#   undef __GR_HAS_CPP
#endif

#endif /* granary_POSIX_TYPES_H_ */
